rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('add_category/', views.add_category, name='add_category'),
]

tango_with_django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static

from rango import views
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

rango/forms.py
from django import forms
from rango.models import Category, Page
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

rango/views.py
from django.shortcuts import render
from rango.models import Category
from rango.forms import CategoryForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from rango.forms import UserForm
from datetime import datetime


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    context_dict = {'categories': category_list}

    visits = int(request.session.get('visits', '0'))
    last_visit = request.session.get('last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")

    if (datetime.now() - last_visit_time).seconds > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit

    request.session['visits'] = visits
    context_dict['visits'] = visits

    return render(request, 'rango/index.html', context=context_dict)



def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
    else:
        user_form = UserForm()

    return render(request,
                  'rango/register.html',
                  {'user_form': user_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,
                            password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('rango:index'))
        else:
            print("Invalid login details")

    return render(request, 'rango/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))



def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})



def about(request):
    return render(request, 'rango/about.html')

templates/rango/about.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
    <title>Rango - About</title>
</head>

<body>
<h1>Rango says...</h1>
<div>
    here is the about page.
</div>

<div>
    This tutorial has been put together by <strong>Efe Doggy Dogg D.O. Double G</strong>
</div>

<div>
    <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
</div>

<div>
    <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />
</div>

<div>
    <a href="{% url 'rango:index' %}">Index</a>
</div>
</body>
</html>

templates/rango/add_category.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Category</title>
</head>
<body>
<h1>Add a Category</h1>

<form method="post" action="/rango/add_category/">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add Category" />
</form>
</body>
</html>

templates/rango/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Rango</title>
</head>
<body>
<div>
    <ul>
        <li><a href="{% url 'rango:index' %}">Home</a></li>
        <li><a href="{% url 'rango:about' %}">About</a></li>
        <li><a href="{% url 'rango:add_category' %}">Add Category</a></li>
    </ul>
</div>

<div>
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>

templates/rango/index.html
{% extends 'rango/base.html' %}

{% block body_block %}
<h1>Rango says...</h1>

<p>Visits: {{ visits }}</p>

{% if categories %}
<ul>
    {% for category in categories %}
    <li>{{ category.name }}</li>
    {% endfor %}
</ul>
{% else %}
<strong>No categories present.</strong>
{% endif %}
{% endblock %}